#!/usr/bin/env node
'use strict';

const path = require('path');
const fs = require('fs');

function cpdir(src, dest) {
	console.log("Copying `" + src + "` to `" + dest + "`");
	try {
		fs.mkdirSync(dest, '0755');
	} catch(e) {
		if (e.code != 'EEXIST') throw e;
	}
	for (const file of fs.readdirSync(src)) {
		var current = fs.lstatSync(path.join(src, file));
		if (current.isDirectory()) {
			cpdir(path.join(src, file), path.join(dest, file));
		} else if (current.isSymbolicLink()) {
			var symlink = fs.readlinkSync(path.join(src, file));
			fs.symlinkSync(symlink, path.join(dest, file));
		} else if (file.endsWith('.js')) {
			const contents = fs.readFileSync(path.join(src, file), 'utf8').replace(/^exports.* = void 0;$/gm, '');
			fs.writeFileSync(path.join(dest, file), contents);
		} else {
			fs.copyFileSync(path.join(src, file),path.join(dest, file));
		}
	}
}
if (process.argv[2] !== 'view') {
	require('child_process').execSync('npm run build', {stdio: 'inherit'});
	
}

cpdir('static', 'out/static');
//cpdir('src/apptest/tests', 'out/apptest/tests');
